### ISSUE TITLE
Program errors with laconic message

### ISSUE THREAD

**Issue by jakobnissen** [GaetanBenoitDev/metaMDBG#10]
I'm running MetaMDBG and get the following output to stderr as the program errors:
```
Input: sample1/tmp//input.txt
Dir: sample1
Minimizer length: 13
Density: 0.005

Checking dependencies: bgzip (wfmash package) ok
Checking dependencies: samtools ok
Checking dependencies: wfmash ok
Checking dependencies: minimap2 ok

Converting reads to minimizers...
N50 read length: 8058
Min k: 4
Max k: 80

Multi-k pass: 4/80

ERROR (logs: sample1/tmp//logs.txt)
```
I've attached the `logs.txt` (but note I had to manually copy-paste it to get it out of our cluster, so some of the lines where it just says the number of reads processed is replaces with [etc])

The input is a 47 GB gzip compressed FASTQ file, and the program is run with 80 GB RAM.
It's possible this is an out of memory-error, so I've rerun it with 1500 GB RAM, however, in that case, the error message is less than perfect.

This is metaMDBG 0.3 running on Linux.

[logs.txt](https://github.com/GaetanBenoitDev/metaMDBG/files/15094176/logs.txt)

**Comment by GaetanBenoitDev** [comment]
Yes it's probably an out of memory exception. I will try to improve the error messages.
