### ISSUE TITLE
Rust implementation?

### ISSUE THREAD

**Issue by jianshu93** [GaetanBenoitDev/metaMDBG#13]
Dear metaMDBG team,

Since the original mDBG was is Rust, would it be possible to add or modified the original version to have a Rust version metaMDBG? rust-mDBG does not work very well for metagenomic assembly but only for high coverage single isolates et.al.  I can imagine it would be extremely useful for a completely Rust based toolbox for metagenomic analysis. 

Thanks,

Jianshu

**Comment by GaetanBenoitDev** [comment]
Dear Jianshu,

It would require months of works to port metaMDBG in rust, so it's unlikely to happen. Conda is your "friend" if you have issues with installations or portability.

Best,
Gaëtan
