### ISSUE TITLE
coverage=0

### ISSUE THREAD

**Issue by rjsorr** [GaetanBenoitDev/metaMDBG#17]
What does coverage=0 mean? 

getting this a lot in larger metagenome assemblies. And how is it estimated (presuming minimap)? Guessing something must be going wrong during generation of the header.

**Comment by GaetanBenoitDev** [comment]
Yes it's based on minimap mapping but it's a rough estimation in my program. I store it using integer so 0 means <1x.

**Comment by GaetanBenoitDev** [comment]
Fixed in new version, now use float
