### ISSUE TITLE
question on how haplotypes were selected/corrected in metaMDBG

### ISSUE THREAD

**Issue by jianshu93** [GaetanBenoitDev/metaMDBG#24]
Dear metaMDBG team,

I am wondering the difference between rust-mdbg and metaMDBG is the same with Flye and metaFlye. Because essentially, when there are difference species in the sample, especially when they are not so closed to each other, the assembly should be the same for each species, the problem came when there are close related species or strains in the same sample. E.g., The most messy part of all long-read assemblers is error-correction in reads that was implicitly developed under the assumption that there are two haplotypes with roughly the same coverage. But in the case of a microbiome, there are bacteria/viruses that share long segments and have vastly different coverages - looks like error-corrections tend to gravitate to the genome with higher coverage and "glue" together two genomes even if there is a possibility to separate them. What do you think? I was asking because I think it should not be very difficult to extend rust-mdbg to have a metagenomic version. 

Thanks,
Jianshu

**Comment by GaetanBenoitDev** [comment]
Hi Jianshu,

Yes, metaMDBG is an assembler for metagenomics data.

MetaMDBG can separate organisms up to ~98% similarity. Strains or close species with more similarity might be collapsed as a single species. We always try to reconstruct the most abundant strain.

If you want to separate strains, there are specific tools like strainberry or floria.
