### ISSUE TITLE
Disabling or changing the correction step (and other performance observations)

### ISSUE THREAD

**Issue by GabeAl** [GaetanBenoitDev/metaMDBG#25]
Hi, 

I was wondering if it is possible to disable read correction (e.g. if using hirro or another correction tool, or when pre-filtering to very high quality reads with v5 SUP basecalling, etc). 

If not, how can it be controlled? I see some interesting options in the commandline that hint at something related to the correction step (e.g. --density-correction), but no way to turn it off (setting this to 0 produces empty assemblies). 

I have noticed, additionally, that raising --density-assembly to a high value (tested with the latest HEAD in github) can lead to some hilarious results, including proclaiming a 6MB genome is a closed 2.3MB genome (I've never seen this kind of thing happen), and other wonky behaviors in the range between 0.02 and 0.05 (higher than that tends to fail outright). 

Any guidance for using these parameters and what your expectations are for tweaking them would be helpful. 

E.g. I'm able to get much better assemblies in low-depth high-accuracy ONT runs when I set the --density-assembly higher (0.01 to 0.02 range) and reduce the min overlap (e.g. to 500bp). The resulting genomes are consistent and seemingly accurate, but the defaults didn't work well in these cases. 

I also saw a question about strain-level assemblies that is quite salient -- would bumping the min read identity help here? What does that do? Does this govern read realignment or initial DBG construction or the error correction step (or all/some of the above)?

I wonder if these observations suggest room for improvement or auto-selection of parameters.

**Comment by GaetanBenoitDev** [comment]
Hi,

Thank you for the detailed feedback.

I have added an option --skip-correction to skip the preliminary read correction.
I think it might create bugs if you use a --density-assembly higher than --density-correction, so now I raise an error. 

I have never tried very high --density-assembly values, but if there is still big issues I will have to check it. This parameter basically represents the fraction of k-mers used for assembly. So using higher density is useful for low-depth organism and strain resolution. But it has a strong impact on runtime and memory usage. The default value 0.005 is a tradeoff for metagenomics. If your input is an isolate genomic dataset, we could definitely optimize the default parameters automatically.

Regarding strain resolution, metaMDBG might not be the best for this has it tries to collapse has much of the diversity at species level (usually metaMDBG resolve species around 97.5% similarity, if two organisms have higher similarity, they might be collapsed as a consensus). Increasing --density-assembly might be helpful for resolving at higher level of similarity. The correction step is also species-level, it might mask the strain level diversity. The parameter --min-read-identity and --min-read-overlap are only for read correction, and you can in fact increase them to be more "strain-sensitive", but not sure that the current consensus method will work at the strain-level.

Hope it helps.

**Comment by GabeAl** [comment]
Awesome!

Using all defaults except changing the density assembly on a test file, I get this:

```
tail */barcode92/*.log
==> m0.005/barcode92/metaMDBG.log <==
        Run time:                   2min 1sec
        Peak memory:                0.66052 GB
        Assembly length:            12898871
        Contigs N50:                3415016
        Nb contigs:                 120
        Nb Contigs (>1Mb):          5
        Nb circular contigs (>1Mb): 0

Contig filename: m0.005/barcode92/contigs.fasta.gz
Done!

==> m0.01/barcode92/metaMDBG.log <==
        Run time:                   5min 16sec
        Peak memory:                1.84612 GB
        Assembly length:            12985867
        Contigs N50:                4627228
        Nb contigs:                 129
        Nb Contigs (>1Mb):          4
        Nb circular contigs (>1Mb): 1

Contig filename: m0.01/barcode92/contigs.fasta.gz
Done!

==> m0.02/barcode92/metaMDBG.log <==
        Run time:                   23min 15sec
        Peak memory:                4.7959 GB
        Assembly length:            11915474
        Contigs N50:                2587639
        Nb contigs:                 146
        Nb Contigs (>1Mb):          4
        Nb circular contigs (>1Mb): 1

Contig filename: m0.02/barcode92/contigs.fasta.gz
Done!
```

This is not unique to this file; this pattern is observable in many isolates and simple mixed communities.

**Comment by GaetanBenoitDev** [comment]
Ok this is interesting. The barcode92 have a consistent assembly length at least. But for the barecode72, 3.3Mb is lost. Is the barcode72 dataset publicly available or available for sharing?

**Comment by GabeAl** [comment]
Good call -- not sure about that one, but I'll try to reproduce on one I can share more easily and get back to you (or get permission to upload it)

**Comment by GabeAl** [comment]
Here you go, here's one I can share. It really does happen a lot though, maybe a fourth or fifth of the time. 

These are both common probiotic Hafnia alvei probiotic strains. Two separate preps, two separate brands, two separate barcodes. 

They should both be roughly 4.7Mb. Flye gets it right, and metaMDBG seems to get it right only in 0.005. In 0.01 it can't close it, and in 0.02 it creates some closed fake franken-genome. :) The second is fragmented in all cases but still gets weirdly collapsed by metaMDBG. 

[metaMDBG-39-0.005.log](https://github.com/user-attachments/files/17878754/metaMDBG-39-0.005.log)
[metaMDBG-39-0.02.log](https://github.com/user-attachments/files/17878755/metaMDBG-39-0.02.log)
[metaMDBG-39-0.01.log](https://github.com/user-attachments/files/17878756/metaMDBG-39-0.01.log)


First, flye. 
```
==> asm/probiotic_39/assembly_info.txt <==
#seq_name       length  cov.    circ.   repeat  mult.   alt_group       graph_path
contig_1        4790255 238     Y       N       1       *       1
contig_2        96475   307     Y       N       1       *       2

==> asm/probiotic_40/assembly_info.txt <==
#seq_name       length  cov.    circ.   repeat  mult.   alt_group       graph_path
contig_1        2790310 162     N       N       1       *       1
contig_2        1408024 140     N       N       1       *       2,4,4
contig_3        529804  151     N       N       1       *       3
contig_5        96482   197     Y       N       1       *       5
contig_6        51132   156     N       N       1       *       6
```

Now the 3 options in metaMDBG. All defaults, 16 threads, just changing the assembly density from 0.005 to 0.01 to 0.02. 
```
==> m0.005/probiotic_39/metaMDBG.log <==
        Run time:                   4min 32sec
        Peak memory:                1.13882 GB
        Assembly length:            4894861
        Contigs N50:                4790254
        Nb contigs:                 3
        Nb Contigs (>1Mb):          1
        Nb circular contigs (>1Mb): 1

Contig filename: m0.005/probiotic_39/contigs.fasta.gz
Done!

==> m0.01/probiotic_39/metaMDBG.log <==
        Run time:                   6min 46sec
        Peak memory:                2.12108 GB
        Assembly length:            4889265
        Contigs N50:                4750498
        Nb contigs:                 4
        Nb Contigs (>1Mb):          1
        Nb circular contigs (>1Mb): 0

Contig filename: m0.01/probiotic_39/contigs.fasta.gz
Done!

==> m0.02/probiotic_39/metaMDBG.log <==
        Run time:                   13min 49sec
        Peak memory:                4.71127 GB
        Assembly length:            3421433
        Contigs N50:                3324961
        Nb contigs:                 2
        Nb Contigs (>1Mb):          1
        Nb circular contigs (>1Mb): 1

Contig filename: m0.02/probiotic_39/contigs.fasta.gz
Done!

$ tail m0*/probiotic_40/*.log
==> m0.005/probiotic_40/metaMDBG.log <==
        Run time:                   2min 21sec
        Peak memory:                0.840268 GB
        Assembly length:            4900611
        Contigs N50:                2942662
        Nb contigs:                 5
        Nb Contigs (>1Mb):          1
        Nb circular contigs (>1Mb): 0

Contig filename: m0.005/probiotic_40/contigs.fasta.gz
Done!

==> m0.01/probiotic_40/metaMDBG.log <==
        Run time:                   3min 57sec
        Peak memory:                1.55926 GB
        Assembly length:            4896220
        Contigs N50:                3468279
        Nb contigs:                 6
        Nb Contigs (>1Mb):          1
        Nb circular contigs (>1Mb): 0

Contig filename: m0.01/probiotic_40/contigs.fasta.gz
Done!

==> m0.02/probiotic_40/metaMDBG.log <==
        Run time:                   9min 22sec
        Peak memory:                3.86656 GB
        Assembly length:            3404481
        Contigs N50:                3308007
        Nb contigs:                 2
        Nb Contigs (>1Mb):          1
        Nb circular contigs (>1Mb): 1

Contig filename: m0.02/probiotic_40/contigs.fasta.gz
Done!
```

Where can I upload/send the fastq files?

**Comment by GabeAl** [comment]
Here's a bacillus too as a bonus (4.2Mb genome, 0.02 makes it 3.3). 

```
$ tail m0*/probiotic_44/*.log
==> m0.005/probiotic_44/metaMDBG.log <==
        Run time:                   1min 45sec
        Peak memory:                0.66032 GB
        Assembly length:            4221045
        Contigs N50:                2135643
        Nb contigs:                 6
        Nb Contigs (>1Mb):          2
        Nb circular contigs (>1Mb): 0

Contig filename: m0.005/probiotic_44/contigs.fasta.gz
Done!

==> m0.01/probiotic_44/metaMDBG.log <==
        Run time:                   2min 24sec
        Peak memory:                1.534 GB
        Assembly length:            4231305
        Contigs N50:                2134606
        Nb contigs:                 6
        Nb Contigs (>1Mb):          2
        Nb circular contigs (>1Mb): 0

Contig filename: m0.01/probiotic_44/contigs.fasta.gz
Done!

==> m0.02/probiotic_44/metaMDBG.log <==
        Run time:                   6min 1sec
        Peak memory:                2.96076 GB
        Assembly length:            3378582
        Contigs N50:                3299337
        Nb contigs:                 3
        Nb Contigs (>1Mb):          1
        Nb circular contigs (>1Mb): 0

Contig filename: m0.02/probiotic_44/contigs.fasta.gz
Done!
```

https://drive.google.com/drive/folders/17hPF8cYRG8L9tsznUlujpMx-Ud_vyUt6?usp=sharing

Please let me know when you download these so I can delete the folder. Thanks!

**Comment by GaetanBenoitDev** [comment]
Thanks a lot, I have the datasets and could reproduce this issue.

**Comment by GaetanBenoitDev** [comment]
I found the bug, I'm still doing testing, I will provide a fix soon.
The bug will only happen at high density indeed, default settings are not impacted.

**Comment by GabeAl** [comment]
Doesn't seem like --skip-correction works. 

`$ metaMDBG asm --in-ont test.fq --out-dir test --skip-correction`
```
Checking dependencies: minimap2
ok

Output dir:              test
Minimizer length:        13
Density correction:      0.025
Density assembly:        0.005
Min read quality:        0
Min read overlap length: 1000
Min read identity:       0.96
Contig Derep threshold:  0.99
Homopolymer compression: 0
Read correction:         1

Converting reads to minimizers

Total read bps:  15854191
N50 read length: 6372
Start k:         4
End k:           63

Correcting reads
Correction skipped
Multi-k pass: 4/63
File not found: test/tmp//read_data_corrected.txt

ERROR (see logs: test/metaMDBG.log)
```

**Comment by GaetanBenoitDev** [comment]
I fixed it, it should also fix the issues with the high --density-assembly.

**Comment by GaetanBenoitDev** [comment]
😅 I think i will never use 16bit integer again 🥲

**Comment by GabeAl** [comment]
Have you considered saturating arithmetic? Megahit uses this, and modern compilers optimize it with an actual saturated add assembly instruction. 

I can easily imagine a case where people get the full 200gb on a single metagenome that is dominated by C dif -- very very easy to get > 4b of a single k-mer there still 😁
