### ISSUE TITLE
Adding metaMDBG stable version on bioconda

### ISSUE THREAD

**Issue by GaetanBenoitDev** [GaetanBenoitDev/metaMDBG#5]
todo

**Comment by hildebra** [comment]
Could the samtools version in the conda receipe be changed to more recent version? Currently this will conflict with many existing environments that a user might want to add metaMDBG to.

e.g. change conda yaml to:
    - wfmash >=0.8.2
    - samtools >=1.6
    - minimap2 >=2.24

**Comment by GaetanBenoitDev** [comment]
I have removed the dependency to samtools and wfmash is the new metaMDBG v1.0
