### ISSUE TITLE
Bug in gfa command in bioconda version

### ISSUE THREAD

**Issue by GaetanBenoitDev** [GaetanBenoitDev/metaMDBG#7]
Because of a code line that I forgot to uncomment, the current bioconda version can't generate assembly graph. I'll fix it in the next version.

**Comment by KelLevick** [comment]
Hello, has this been fixed yet? I am getting an "Invalid assembly dir" error when I run gfa in the same folder as my contigs file. Is this the same bug you found?

**Comment by GaetanBenoitDev** [comment]
It is fixed but not in the bioconda version.
You can install from source using the commands in "Building from source (using conda)"

**Comment by GaetanBenoitDev** [comment]
Fixed in v1.0
